[project]
name = "simple-mcp-server"
version = "0.1.0"
description = "シンプルなFastMCPサーバー - 個人用ローカルツール"
requires-python = ">=3.8"
dependencies = [
    "fastmcp>=2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []
